---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0627backend-webappdeployment
spec:
   replicas: 1
   strategy:
     type: Recreate
   selector:
     matchLabels:
       app: 0627backend
   template:
     metadata:
       name: 0627backendpod
       labels:
        app: 0627backend
     spec:
       containers:
      - name: 0627backendcontainer
        image: vaishnavi062/0627backend
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
   name: 0627backendsvc
spec:
   type: NodePort
   selector:
    app: 0627backend
   ports:
   - port: 80
     targetPort: 8080

...
